spring:
  application:
    name: cloud-storage-service

  datasource:
    url: ${CSS_SQL_DATASOURCE:dbc:mysql://localhost:3306/cloudstoragedb}
    username: ${CSS_SQL_USERNAME:app_user}
    password: ${CSS_SQL_PASSWORD:app_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none # Prevent Hibernate from altering the schema, since Flyway handles migrations
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 2660
  error:
    include-message: always

blob-storage:
  azure:
    key: ${AZURE_STORAGE_CONNECTION_STRING}